version: '3.9'

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=MASTER_KEY
    ports:
      - "7700:7700"
    volumes:
      - /meili_data:/meili_data